# Generated by Django 4.0.3 on 2022-04-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bunga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=100)),
                ('nama_latin', models.CharField(default='', max_length=100)),
                ('images', models.ImageField(null=True, upload_to='static/images')),
                ('cara_perawatan', models.CharField(default='', max_length=500)),
                ('jenis_tanaman', models.CharField(default='', max_length=100)),
                ('jumlah', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
