# Generated by Django 4.0.3 on 2022-04-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunga',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
